name: Linux CI Tests

on: 
  pull_request:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Same repo
      - uses: actions/checkout@v2
        if: >-
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.full_name == github.repository
      
      # Forked repo
      - uses: actions/checkout@v2
        #with:
        #  ref: ${{ github.event.pull_request.head.ref }}
        #  repository: ${{ github.event.pull_request.head.repo.full_name }}
        if: >-
          github.event_name == 'pull_request_target' &&
          github.event.pull_request.head.repo.full_name != github.repository

      - name: Style Check
        run: sudo bash -c echo "Style Check"
        if: >-
          (
            github.event_name == 'pull_request' &&
            github.event.pull_request.head.repo.full_name == github.repository
          ) || (
            github.event_name == 'pull_request_target' &&
            github.event.pull_request.head.repo.full_name != github.repository
          )

      - name: Submodules Init
        uses: snickerbockers/submodules-init@v4
        if: >-
          (
            github.event_name == 'pull_request' &&
            github.event.pull_request.head.repo.full_name == github.repository
          ) || (
            github.event_name == 'pull_request_target' &&
            github.event.pull_request.head.repo.full_name != github.repository
          )

      - name: Configure
        run: sudo bash -c echo "Configure"
        if: >-
          (
            github.event_name == 'pull_request' &&
            github.event.pull_request.head.repo.full_name == github.repository
          ) || (
            github.event_name == 'pull_request_target' &&
            github.event.pull_request.head.repo.full_name != github.repository
          )

      - name: Fetch FreeRTOS
        run: sudo bash -c echo "Fetch FreeRTOS"
        if: >-
          (
            github.event_name == 'pull_request' &&
            github.event.pull_request.head.repo.full_name == github.repository
          ) || (
            github.event_name == 'pull_request_target' &&
            github.event.pull_request.head.repo.full_name != github.repository
          )

      - name: Build with Clang
        run: sudo bash -c echo "Build with Clang"
        if: >-
          (
            github.event_name == 'pull_request' &&
            github.event.pull_request.head.repo.full_name == github.repository
          ) || (
            github.event_name == 'pull_request_target' &&
            github.event.pull_request.head.repo.full_name != github.repository
          )

      - name: Check-in Tests
        run: sudo bash -c echo "Check-in Tests"
        if: >-
          (
            github.event_name == 'pull_request' &&
            github.event.pull_request.head.repo.full_name == github.repository
          ) || (
            github.event_name == 'pull_request_target' &&
            github.event.pull_request.head.repo.full_name != github.repository
          )
